# Lab | Transformers

---

### Section structure

1. The open-source ecosystem: increasing accessibility to machine learning (ML) software and hardware
2. Some simple code demonstrations
3. Q&A

## 1. Ease-of-use: Using Transformers in 3 lines of code


**Overview of different tasks that can be automated with ML**
* Key ingredients: (1) a model trained on a specific task; (2) input data (e.g. texts or images); (3) output produced by the model.
* Transformers are currently the most popular type of deep learning algorithm. Most tasks below are solved with Transformers. There might be other types of algorithms coming up in the medium term.

**Install the Transformers library & dependencies**

In [3]:
!pip install transformers
!pip install sentencepiece
!pip install wikipedia
!pip install accelerate
!pip install tf-keras
!pip install torch

Requirement already satisfied: transformers in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (5.12.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: numpy>=1.17 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (2.2.6)
Requirement already satisfied: tqdm>=4.60 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (4.68.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: packaging>=20.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (26.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from transformers) (1.19.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.3)
Requirement already satisfied: click>=8.4.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: colorama in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: certifi in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: anyio in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: idna in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: httpcore==1.* in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: sentencepiece in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (0.2.1)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: wikipedia in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from wikipedia) (4.15.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from wikipedia) (2.34.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.18)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2026.5.20)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from beautifulsoup4->wikipedia) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from beautifulsoup4->wikipedia) (4.15.0)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: accelerate in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (1.14.0)
Requirement already satisfied: numpy>=1.17 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (2.2.6)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (1.19.0)
Requirement already satisfied: torch>=2.0.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (2.12.0)
Requirement already satisfied: pyyaml in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: psutil in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (7.2.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (0.8.0)
Requirement already satisfied: packaging>=20.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from accelerate) (26.2)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.68.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.4.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.29.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.25.1)
Requirement already satisfied: click>=8.4.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.5.1)
Requirement already satisfied: colorama in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from click>=8.4.0->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: idna in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.18)
Requirement already satisfied: httpcore==1.* in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: anyio in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.13.0)
Requirement already satisfied: certifi in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.5.20)
Requirement already satisfied: h11>=0.16 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: sympy>=1.13.3 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: setuptools<82 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch>=2.0.0->accelerate) (57.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: rich>=13.8.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: tf-keras in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (2.21.0)
Requirement already satisfied: tensorflow<2.22,>=2.21 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tf-keras) (2.21.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (4.15.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.3.0)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.6.3)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.2.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.12.2)
Requirement already satisfied: libclang>=13.0.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (18.1.1)
Requirement already satisfied: six>=1.12.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.17.0)
Requirement already satisfied: packaging in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (7.35.1)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.7.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.81.1)
Requirement already satisfied: setuptools in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (57.4.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.2.6)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (25.12.19)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.5.4)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.2.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.14.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.34.2)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.4.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.22,>=2.21->tf-keras) (0.47.0)
Requirement already satisfied: namex in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.1.0)
Requirement already satisfied: rich in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (15.0.0)
Requirement already satisfied: optree in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (2.7.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.1.2)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: torch in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (2.12.0)
Requirement already satisfied: filelock in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (3.29.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (2026.4.0)
Requirement already satisfied: setuptools<82 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (57.4.0)
Requirement already satisfied: jinja2 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: sympy>=1.13.3 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\swapr\desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages (from jinja2->torch) (3.0.3)

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'C:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\Scripts\python.exe -m pip install --upgrade pip' command.

**The Hugging Face Pipeline**
* Makes automation of many NLP tasks possible in 3 lines of code
* Detailed documentation is available [here](https://huggingface.co/transformers/main_classes/pipelines.html)

In [1]:
from transformers import pipeline
import pandas as pd
import numpy as np
from pprint import pprint

c:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Note : You might need more libraries or updates to run the cells below, if that is the case, follow the error messages and pip install accordingly. Chat gpt can help you if given the error messages.

### 2.1 Many models tailored to specific tasks

#### 2.1.1 Text classification

Let's select a popular text classification model in the [HF model hub](https://huggingface.co/models?pipeline_tag=text-classification&sort=downloads).

Here we chose "cardiffnlp/twitter-roberta-base-irony".

We will classify text into ironic or non ironic.

In [2]:
pipeline_classification = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-irony")  # cardiffnlp/twitter-roberta-base-irony, SamLowe/roberta-base-go_emotions

Now that we have the model we can pass it a string and have it give us a classification.

Feel free to experiment with different sentences by changing the contents of the variable text

In [3]:
text = "Well that workshop was totally worth my time..."  # "Well that workshop was totally worth my time..."  "This smells weird, I'm not sure if I should eat this ... Yikes, it tasted like old socks!"
output = pipeline_classification(text, top_k=10)
print(output)

[{'label': 'irony', 'score': 0.9424386620521545}, {'label': 'non_irony', 'score': 0.057561349123716354}]

Let's make the output a little cleaner

In [4]:
# make output a bit cleaner
df_output = pd.DataFrame(output)
print(df_output)

       label     score
0      irony  0.942439
1  non_irony  0.057561

In [5]:
from transformers import pipeline
print("pipeline imported")

pipeline imported

As you can see, in a few lines of code and by leveraging an existing model we can classify text as ironic or non ironic. Now you have one more tool in your machine learning toolbox.

Remember that : 'when you only have a hammer everything is a nail'. But if we want to build a house (perform machine learning the right way), we need to use the right tool for the right job.

#### 2.1.2 Machine Translation

* Open source machine translation (MT) models enable you to translate between many different languages without Google Translate.
* [University of Helsinki](https://huggingface.co/Helsinki-NLP) uploaded models for more than 1000 language pairs to the Hugging Face hub
* [Facebook AI](https://huggingface.co/models?search=facebook+m2m) open-sourced several multi-lingual models
* The [EasyNMT library](https://github.com/UKPLab/EasyNMT), provides an easy wrapper for all these models
* Most machine translation models translate between two languages in one direction (e.g. German to English, but not English to German), some can translate in multiple directions.

In [10]:
# translation pipeline docs: https://huggingface.co/transformers/main_classes/pipelines.html#transformers.TranslationPipeline
from transformers import pipeline

pipeline_translate = pipeline("translation", model="facebook/m2m100_418M")

M2M100 is a multilingual encoder-decoder (seq-to-seq) model trained for Many-to-Many multilingual translation.

The model that can directly translate between the 9,900 directions of 100 languages.

Here we specify to translate from German 'de' to English 'en'

In [11]:
text = "Ich bin ein Fisch"
pipeline_translate(text, src_lang="de", tgt_lang="en")

[{'translation_text': 'I am a fish'}]

Let's do the same but with and entire wikipedia page in german.

In [14]:
# download any text from wikipedia, via  https://pypi.org/project/wikipedia/
import wikipedia
wikipedia.set_lang("de")

text = wikipedia.summary("Donald Trump").replace('\n', ' ')[:318]
print(f"Original text:\n{text}\n")

# translate the text from wikipedia
text_translated = pipeline_translate(text, src_lang="de", tgt_lang="en")
print(f"Translated text:\n{text_translated[0]['translation_text']}")

Original text:
Donald John Trump [ˈdɑn.əld dʒɑn tɹɐmp] (* 14. Juni 1946 in New York City) ist ein US-amerikanischer Politiker der Republikanischen Partei. Er war von 2017 bis 2021 der 45. und ist seit dem 20. Januar 2025 der 47. Präsident der Vereinigten Staaten. Außerdem ist er Unternehmer und ehemaliger Showmaster. Er gilt als ei

Translated text:
Donald John Trump [ˈdɑn.əld dʒɑn tɔmp] (* 14 June 1946 in New York City) is an American politician of the Republican Party. he was from 2017 to 2021 the 45th and is from 20 January 2025 the 47th President of the United States.

#### 2.1.3 Text Summarization

In [13]:
# docs for summarisation pipeline: https://huggingface.co/transformers/main_classes/pipelines.html#summarizationpipeline
pipeline_summarize = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")  # sshleifer/distilbart-cnn-12-6 , google/pegasus-cnn_dailymail

In [16]:
pipeline_summarize("This is a test sentence.", max_length=20, min_length=5)

Your max_length is set to 20, but your input_length is only 8. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=4)

[{'summary_text': " This is a test sentence. This is the first time I've seen this sentence ."}]

In [17]:
# download any long text from wikipedia, via  https://pypi.org/project/wikipedia/
import wikipedia
wikipedia.set_lang("en")

text_long = wikipedia.summary("Donald Trump").replace('\n', ' ')
print(f"Original text:\n{text_long}\n")

# translate the text from wikipedia
text_summarized = pipeline_summarize(text_long, min_length=5, max_length=30)
print(f"Summarized text:\n{text_summarized[0]['summary_text']}")

Original text:
Donald John Trump (born June 14, 1946) is an American politician, media personality, and businessman who is the 47th president of the United States. A member of the Republican Party, he served as the 45th president from 2017 to 2021. Born into a wealthy New York City family, Trump graduated from the University of Pennsylvania in 1968 with a bachelor's degree in economics. He became the president of his family's real estate business in 1971, renamed it the Trump Organization, and began acquiring and building skyscrapers, hotels, casinos, and golf courses. He launched side ventures, many licensing the Trump name, and filed for six business bankruptcies in the 1990s and 2000s. From 2004 to 2015, he hosted the reality television show The Apprentice, bolstering his fame as a billionaire. Presenting himself as a political outsider, Trump won the 2016 presidential election against Democratic Party nominee Hillary Clinton. During his first presidency, Trump imposed a travel ban on seven Muslim-majority countries, expanded the Mexico–United States border wall, and enforced a family separation policy on the border. He rolled back environmental and business regulations, signed the Tax Cuts and Jobs Act, and appointed three Supreme Court justices. He withdrew the U.S. from agreements on climate and trade, and started a trade war with China. In response to the COVID-19 pandemic in 2020, he downplayed its severity, contradicted health officials, and signed the CARES Act. After losing the 2020 presidential election to Joe Biden, Trump refused to concede defeat and attempted to overturn the result, culminating in the January 6 Capitol attack in 2021. He was impeached twice—in 2019 for abuse of power and obstruction of Congress and in 2021 for incitement of insurrection—and acquitted by the Senate both times. In 2023, Trump was found liable in New York state civil cases for sexual abuse and defamation and for business fraud. In May 2024, he was found guilty in a New York state court on 34 counts of falsifying business records, making him the first U.S. president convicted of a felony. After winning the 2024 presidential election against Vice President Kamala Harris, he was given a no-penalty sentence, and two federal felony indictments for retention of classified documents and obstruction of the 2020 election were dismissed without prejudice. Trump began his second presidency by initiating mass layoffs of federal workers. He imposed tariffs on nearly all countries at the highest level since the Great Depression and signed the One Big Beautiful Bill Act. His administration's actions—including the targeting of political opponents and civil society, restriction of transgender rights, mass deportation of undocumented immigrants, and extensive use of executive orders—have drawn over 550 lawsuits challenging their legality. In Latin America, he pursued a campaign to attack alleged drug traffickers, and ordered a military raid into Venezuela to capture the country's president. In February 2026, he authorized joint U.S.–Israeli strikes on Iran that resulted in the 2026 Iran war. Since 2015, Trump's leadership style and political agenda—often referred to as Trumpism—have reshaped the Republican Party's identity. Many of his comments and actions have been characterized as racist or misogynistic. He has made many false or misleading statements during his campaigns and presidency, to a degree unprecedented in American politics, and promotes conspiracy theories. Trump's actions have been described by researchers as authoritarian and contributing to democratic backsliding. After his first term, scholars and historians ranked him as one of the worst presidents in American history.

Summarized text:
 Donald John Trump is the 47th president of the United States . He served as the 45th president from 2017 to 2021 . He was

#### 2.1.4 Named Entity Recognition

NER is a task that involves identifying and classifying specific entities in text into predefined categories, such as names of people, organizations, locations, dates, and more. 

For example, in the sentence "Apple Inc. was founded by Steve Jobs in California," NER would recognize "Apple Inc." as an organization, "Steve Jobs" as a person, and "California" as a location.

In [18]:
pipeline_ner = pipeline("token-classification", model="dslim/bert-base-NER-uncased", aggregation_strategy="simple")

config.json: 1.26kB [00:00, 1.26MB/s]
c:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\swapr\.cache\huggingface\hub\models--dslim--bert-base-NER-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
model.safetensors: 100%|██████████| 438M/438M [00:10<00:00, 42.8MB/s]
Some weights of the model checkpoint at dslim/bert-base-NER-uncased were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
tokenizer_config.json: 100%|██████████| 39.0/39.0 [00:00<?, ?B/s]
vocab.txt: 232kB [00:00, 5.73MB/s]
special_tokens_map.json: 100%|██████████| 112/112 [00:00<?, ?B/s]

In [19]:
import wikipedia
wikipedia.set_lang("en")

text_long = wikipedia.summary("Donald Trump").replace('\n', ' ')

output = pipeline_ner(text_long)

pd.DataFrame(output)

   entity_group     score                        word  start   end
0           PER  0.984957           donald john trump      0    17
1          MISC  0.984379                    american     45    53
2           LOC  0.988764               united states    134   147
3          MISC  0.822807                  republican    165   175
4           ORG  0.680197                       party    176   181
5           LOC  0.880766               new york city    254   267
6           PER  0.976201                       trump    276   281
7           ORG  0.674295  university of pennsylvania    301   327
8           ORG  0.848118          trump organization    460   478
9           PER  0.870318                       trump    607   612
10         MISC  0.937434              the apprentice    740   754
11          PER  0.989030                       trump    838   843
12         MISC  0.983709                  democratic    887   897
13          PER  0.992693             hillary clinton    912   927
14          PER  0.981538                       trump    958   963
15         MISC  0.992487                      muslim    994  1000
16          LOC  0.989548                      mexico   1034  1040
17          LOC  0.994289               united states   1041  1054
18         MISC  0.967873       tax cuts and jobs act   1189  1210
19          ORG  0.936530               supreme court   1232  1245
20          LOC  0.921955                       u. s.   1272  1276
21          LOC  0.996102                       china   1344  1349
22         MISC  0.876986                  covid - 19   1370  1378
23         MISC  0.956980                   cares act   1471  1480
24          PER  0.950111                   joe biden   1529  1538
25          PER  0.973055                       trump   1540  1545
26          LOC  0.721628                     capitol   1639  1646
27          ORG  0.594793                    congress   1732  1740
28          ORG  0.986240                      senate   1805  1811
29          PER  0.984726                       trump   1833  1838
30          LOC  0.805394              new york state   1859  1873
31          LOC  0.978407                    new york   1980  1988
32          LOC  0.849349                       u. s.   2067  2071
33          PER  0.996500                       kamal   2173  2178
34          PER  0.983292                  ##a harris   2178  2186
35          PER  0.988296                       trump   2368  2373
36         MISC  0.974637            great depression   2523  2539
37         MISC  0.973808  one big beautiful bill act   2555  2581

### 2.2. Universal models

The models mentioned above are designed to excel at a single specific task on a particular dataset. The key advantage of these models is their high performance and accuracy on that specific task and dataset. 

However, in real-world applications, the problems you'll face often require solving slightly different tasks, possibly with varied category definitions or applied to different types of texts.

Universal models can help address this challenge. Although they also focus on one task, the task is general or universal enough that many other tasks can be reformulated into it. Two examples of universal tasks are:

- Natural Language Inference (NLI): A task that can effectively solve a wide range of classification tasks by determining whether a given premise supports, contradicts, or is neutral with respect to a hypothesis.

- Token Generation: An even more universal task that can be applied to solve virtually any text-related task, including translation, summarization, and text completion.

These universal tasks enable the models to be versatile and adaptable to various problems beyond the specific ones they were initially trained on.

#### Zero-shot classification


Zero-shot classification is a technique where a model can categorize data into classes it has never seen before. 

Instead of relying on labeled examples for each class, the model understands the relationship between the input and the class descriptions, allowing it to make accurate predictions without needing specific training on those classes.

In [20]:
pipeline_zeroshot_classification = pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")

config.json: 1.07kB [00:00, 1.07MB/s]
c:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\swapr\.cache\huggingface\hub\models--MoritzLaurer--mDeBERTa-v3-base-mnli-xnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
model.safetensors: 100%|██████████| 558M/558M [00:17<00:00, 32.0MB/s]
tokenizer_config.json: 1.26kB [00:00, ?B/s]
spm.model: 100%|██████████| 4.31M/4.31M [00:02<00:00, 1.67MB/s]
tokenizer.json: 100%|██████████| 16.3M/16.3M [00:00<00:00, 35.7MB/s]
added_tokens.json: 100%|██████████| 23.0/23.0 [00:00<?, ?B/s]
special_tokens_map.json: 100%|██████████| 286/286 [00:00<00:00, 282kB/s]

Here we will give the model a list of classes ('payment issues', 'travel advice', 'bug report') for it to classify our string.

In [21]:
text = "Customer: I have not received my reimbursement yet. What the hell is going on?"
classes = ['payment issues', 'travel advice', 'bug report']  # "account opening", "customer complaint"

#text = "I do not think the government is trustworthy anymore. We need to mobilize and resist!"
#classes = ["civil disobedience", "praise of the government", "travel advice"]  # "collective action"

output = pipeline_zeroshot_classification(text, classes, multi_label=True)

pd.DataFrame(data=[output["labels"], output["scores"]], index=["class", "probability"]).T

            class probability
0  payment issues    0.991133
1      bug report    0.076115
2   travel advice    0.018696

## Exercise

Now it is your turn to go to the hugging face library https://huggingface.co/models?pipeline_tag=text-classification&sort=downloads

(you can select on the left menu of the website the type of NLP tasks you want models to perform)

- Find an NLP model that we have not used previously.

- Get some data from wikipedia or elsewhere.

- Perform inference with the model and print the result!

- Comment your code along the way, describe what your model does and what your end goal is from input to output.

Have fun!

In [22]:
# Your code here :
# 1. Import libraries
from transformers import pipeline
import wikipedia

# 2. Set Wikipedia language and download a long article
wikipedia.set_lang("en")
topic = "Artificial intelligence"
text_long = wikipedia.summary(topic).replace("\n", " ")

print(f"Original topic: {topic}\n")
print(f"Sample of text:\n{text_long[:400]}...\n")

# 3. Build a zero-shot text classification pipeline
#    Model: facebook/bart-large-mnli
#    Task: given some candidate labels, decide which ones best describe the text.
classifier = pipeline(
    task="zero-shot-classification",
    model="facebook/bart-large-mnli"
)

# 4. Define candidate labels (our "end goal" categories)
candidate_labels = ["technology", "politics", "sports", "entertainment", "health"]

# 5. Run inference: classify the Wikipedia text into our custom labels
result = classifier(
    sequences=text_long,
    candidate_labels=candidate_labels,
    multi_label=True  # allow multiple labels to be true at the same time
)

# 6. Print the result in a readable way
print("Classification result:")
for label, score in zip(result["labels"], result["scores"]):
    print(f"- {label:12s}: {score:.3f}")

Original topic: Artificial intelligence

Sample of text:
Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in engineering, mathematics and computer science that develops and studies methods and software that enable machines to perceive their environment and use learn...

config.json: 1.15kB [00:00, ?B/s]
c:\Users\swapr\Desktop\bootcamp\labs\week18\lab-transformers\venv310\lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\swapr\.cache\huggingface\hub\models--facebook--bart-large-mnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
model.safetensors: 100%|██████████| 1.63G/1.63G [00:49<00:00, 33.1MB/s]
tokenizer_config.json: 100%|██████████| 26.0/26.0 [00:00<00:00, 25.8kB/s]
vocab.json: 899kB [00:00, 15.4MB/s]
merges.txt: 456kB [00:00, 47.6MB/s]
tokenizer.json: 1.36MB [00:00, 52.2MB/s]

Classification result:
- technology  : 0.938
- entertainment: 0.314
- health      : 0.212
- politics    : 0.109
- sports      : 0.045